/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsUdaipurRouteImport } from './routes/destinations/udaipur'
import { Route as DestinationsSariskaRouteImport } from './routes/destinations/sariska'
import { Route as DestinationsRanthamboreRouteImport } from './routes/destinations/ranthambore'
import { Route as DestinationsPushkarRouteImport } from './routes/destinations/pushkar'
import { Route as DestinationsKumbalgarhRouteImport } from './routes/destinations/kumbalgarh'
import { Route as DestinationsJodhpurRouteImport } from './routes/destinations/jodhpur'
import { Route as DestinationsJawaiRouteImport } from './routes/destinations/jawai'
import { Route as DestinationsJaisalmerRouteImport } from './routes/destinations/jaisalmer'
import { Route as DestinationsJaipurRouteImport } from './routes/destinations/jaipur'
import { Route as DestinationsBikanerRouteImport } from './routes/destinations/bikaner'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsUdaipurRoute = DestinationsUdaipurRouteImport.update({
  id: '/destinations/udaipur',
  path: '/destinations/udaipur',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSariskaRoute = DestinationsSariskaRouteImport.update({
  id: '/destinations/sariska',
  path: '/destinations/sariska',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRanthamboreRoute = DestinationsRanthamboreRouteImport.update({
  id: '/destinations/ranthambore',
  path: '/destinations/ranthambore',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsPushkarRoute = DestinationsPushkarRouteImport.update({
  id: '/destinations/pushkar',
  path: '/destinations/pushkar',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsKumbalgarhRoute = DestinationsKumbalgarhRouteImport.update({
  id: '/destinations/kumbalgarh',
  path: '/destinations/kumbalgarh',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsJodhpurRoute = DestinationsJodhpurRouteImport.update({
  id: '/destinations/jodhpur',
  path: '/destinations/jodhpur',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsJawaiRoute = DestinationsJawaiRouteImport.update({
  id: '/destinations/jawai',
  path: '/destinations/jawai',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsJaisalmerRoute = DestinationsJaisalmerRouteImport.update({
  id: '/destinations/jaisalmer',
  path: '/destinations/jaisalmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsJaipurRoute = DestinationsJaipurRouteImport.update({
  id: '/destinations/jaipur',
  path: '/destinations/jaipur',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsBikanerRoute = DestinationsBikanerRouteImport.update({
  id: '/destinations/bikaner',
  path: '/destinations/bikaner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations/bikaner': typeof DestinationsBikanerRoute
  '/destinations/jaipur': typeof DestinationsJaipurRoute
  '/destinations/jaisalmer': typeof DestinationsJaisalmerRoute
  '/destinations/jawai': typeof DestinationsJawaiRoute
  '/destinations/jodhpur': typeof DestinationsJodhpurRoute
  '/destinations/kumbalgarh': typeof DestinationsKumbalgarhRoute
  '/destinations/pushkar': typeof DestinationsPushkarRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/sariska': typeof DestinationsSariskaRoute
  '/destinations/udaipur': typeof DestinationsUdaipurRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations/bikaner': typeof DestinationsBikanerRoute
  '/destinations/jaipur': typeof DestinationsJaipurRoute
  '/destinations/jaisalmer': typeof DestinationsJaisalmerRoute
  '/destinations/jawai': typeof DestinationsJawaiRoute
  '/destinations/jodhpur': typeof DestinationsJodhpurRoute
  '/destinations/kumbalgarh': typeof DestinationsKumbalgarhRoute
  '/destinations/pushkar': typeof DestinationsPushkarRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/sariska': typeof DestinationsSariskaRoute
  '/destinations/udaipur': typeof DestinationsUdaipurRoute
  '/destinations': typeof DestinationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations/bikaner': typeof DestinationsBikanerRoute
  '/destinations/jaipur': typeof DestinationsJaipurRoute
  '/destinations/jaisalmer': typeof DestinationsJaisalmerRoute
  '/destinations/jawai': typeof DestinationsJawaiRoute
  '/destinations/jodhpur': typeof DestinationsJodhpurRoute
  '/destinations/kumbalgarh': typeof DestinationsKumbalgarhRoute
  '/destinations/pushkar': typeof DestinationsPushkarRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/sariska': typeof DestinationsSariskaRoute
  '/destinations/udaipur': typeof DestinationsUdaipurRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations/bikaner'
    | '/destinations/jaipur'
    | '/destinations/jaisalmer'
    | '/destinations/jawai'
    | '/destinations/jodhpur'
    | '/destinations/kumbalgarh'
    | '/destinations/pushkar'
    | '/destinations/ranthambore'
    | '/destinations/sariska'
    | '/destinations/udaipur'
    | '/destinations/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/destinations/bikaner'
    | '/destinations/jaipur'
    | '/destinations/jaisalmer'
    | '/destinations/jawai'
    | '/destinations/jodhpur'
    | '/destinations/kumbalgarh'
    | '/destinations/pushkar'
    | '/destinations/ranthambore'
    | '/destinations/sariska'
    | '/destinations/udaipur'
    | '/destinations'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/destinations/bikaner'
    | '/destinations/jaipur'
    | '/destinations/jaisalmer'
    | '/destinations/jawai'
    | '/destinations/jodhpur'
    | '/destinations/kumbalgarh'
    | '/destinations/pushkar'
    | '/destinations/ranthambore'
    | '/destinations/sariska'
    | '/destinations/udaipur'
    | '/destinations/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsBikanerRoute: typeof DestinationsBikanerRoute
  DestinationsJaipurRoute: typeof DestinationsJaipurRoute
  DestinationsJaisalmerRoute: typeof DestinationsJaisalmerRoute
  DestinationsJawaiRoute: typeof DestinationsJawaiRoute
  DestinationsJodhpurRoute: typeof DestinationsJodhpurRoute
  DestinationsKumbalgarhRoute: typeof DestinationsKumbalgarhRoute
  DestinationsPushkarRoute: typeof DestinationsPushkarRoute
  DestinationsRanthamboreRoute: typeof DestinationsRanthamboreRoute
  DestinationsSariskaRoute: typeof DestinationsSariskaRoute
  DestinationsUdaipurRoute: typeof DestinationsUdaipurRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/udaipur': {
      id: '/destinations/udaipur'
      path: '/destinations/udaipur'
      fullPath: '/destinations/udaipur'
      preLoaderRoute: typeof DestinationsUdaipurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/sariska': {
      id: '/destinations/sariska'
      path: '/destinations/sariska'
      fullPath: '/destinations/sariska'
      preLoaderRoute: typeof DestinationsSariskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/ranthambore': {
      id: '/destinations/ranthambore'
      path: '/destinations/ranthambore'
      fullPath: '/destinations/ranthambore'
      preLoaderRoute: typeof DestinationsRanthamboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/pushkar': {
      id: '/destinations/pushkar'
      path: '/destinations/pushkar'
      fullPath: '/destinations/pushkar'
      preLoaderRoute: typeof DestinationsPushkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/kumbalgarh': {
      id: '/destinations/kumbalgarh'
      path: '/destinations/kumbalgarh'
      fullPath: '/destinations/kumbalgarh'
      preLoaderRoute: typeof DestinationsKumbalgarhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/jodhpur': {
      id: '/destinations/jodhpur'
      path: '/destinations/jodhpur'
      fullPath: '/destinations/jodhpur'
      preLoaderRoute: typeof DestinationsJodhpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/jawai': {
      id: '/destinations/jawai'
      path: '/destinations/jawai'
      fullPath: '/destinations/jawai'
      preLoaderRoute: typeof DestinationsJawaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/jaisalmer': {
      id: '/destinations/jaisalmer'
      path: '/destinations/jaisalmer'
      fullPath: '/destinations/jaisalmer'
      preLoaderRoute: typeof DestinationsJaisalmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/jaipur': {
      id: '/destinations/jaipur'
      path: '/destinations/jaipur'
      fullPath: '/destinations/jaipur'
      preLoaderRoute: typeof DestinationsJaipurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/bikaner': {
      id: '/destinations/bikaner'
      path: '/destinations/bikaner'
      fullPath: '/destinations/bikaner'
      preLoaderRoute: typeof DestinationsBikanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsBikanerRoute: DestinationsBikanerRoute,
  DestinationsJaipurRoute: DestinationsJaipurRoute,
  DestinationsJaisalmerRoute: DestinationsJaisalmerRoute,
  DestinationsJawaiRoute: DestinationsJawaiRoute,
  DestinationsJodhpurRoute: DestinationsJodhpurRoute,
  DestinationsKumbalgarhRoute: DestinationsKumbalgarhRoute,
  DestinationsPushkarRoute: DestinationsPushkarRoute,
  DestinationsRanthamboreRoute: DestinationsRanthamboreRoute,
  DestinationsSariskaRoute: DestinationsSariskaRoute,
  DestinationsUdaipurRoute: DestinationsUdaipurRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
