name: tiv-rajasthan

services:
  postgres:
    image: postgres
    container_name: tiv-rajasthan-postgres
    environment:
      POSTGRES_DB: tiv-rajasthan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - tiv-rajasthan_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  tiv-rajasthan_postgres_data:
